name:                json-parser
version:             0.1.0.0
github:              "abhin4v/hs-json-parser"
license:             BSD3
author:              "Abhinav Sarkar"
maintainer:          "abhinav@abhinavsarkar.net"
copyright:           "2018 Abhinav Sarkar"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/abhin4v/hs-json-parser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: []
  exposed-modules:
    - JSONParser
  ghc-options:
  - -Wall

executables:
  ppj:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -O2
    dependencies:
    - json-parser
    - pretty-simple

tests:
  json-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: -O2
    dependencies:
    - json-parser
    - QuickCheck
